### PR TITLE
Stick tcc-816 with official tinycc project, for futur migration

### PR DESCRIPTION
**Pull request by kobenairb**
Hi,

 Here a big PR to prepare the migration of tcc-816 in 0.9.24 from tinycc. Nothing changes, it's just formatting and the integration of tinycc (missing pieces of code) to tcc-816. Everything is tested.

 More details on how I did it below.

# Migration of tcc-816 to new version of tinycc

- [Migration of tcc-816 to new version of tinycc](#migration-of-tcc-816-to-new-version-of-tinycc)
  - [My working environment under vscode](#my-working-environment-under-vscode)
    - [Add-ons installed for vscode](#add-ons-installed-for-vscode)
  - [List of steps performed](#list-of-steps-performed)
    - [Step 1: Remove excess spaces and format in Unix format](#step-1-remove-excess-spaces-and-format-in-unix-format)
      - [pvsneslib/compiler/tcc-816 side](#pvsneslibcompilertcc-816-side)
      - [Tinycc side](#tinycc-side)
    - [Step 2: Use vscode to reformat .c and .h files](#step-2-use-vscode-to-reformat-c-and-h-files)
    - [Step 3: Diff et Merge](#step-3-diff-et-merge)
  - [Test changes](#test-changes)
  - [Other Changes](#other-changes)
  - [Next step to do: migrate to 0.9.24 of tinycc](#next-step-to-do-migrate-to-0924-of-tinycc)

### Add-ons installed for vscode

```
code --list-extensions | xargs -L 1 echo code --install-extension | awk '{print $3}'
bbenoist.Doxygen
cismonx.texinfo
eamodio.gitlens
Equinusocio.vsc-community-material-theme
Equinusocio.vsc-material-theme
esbenp.prettier-vscode
fabiospampinato.vscode-diff
foxundermoon.shell-format
GitHub.vscode-pull-request-github
henriiik.docker-linter
maziac.asm-code-lens
mhutchie.git-graph
ms-azuretools.vscode-docker
ms-python.python
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-vscode.cmake-tools
ms-vscode.cpptools
ms-vscode.cpptools-extension-pack
ms-vscode.cpptools-themes
ParthR2031.colorful-comments
pejmannikram.vscode-auto-scroll
PKief.material-icon-theme
sfodje.perltidy
timonwong.shellcheck
twxs.cmake
VisualStudioExptTeam.vscodeintellicode
yzhang.markdown-all-in-one
```
My vscode configurations in my workspace (settings.json)

```
{
    // trim trailing whitespace on save.
    "files.trimTrailingWhitespace": true,
    // The number of spaces a tab is equal to.
    "editor.tabSize": 4,
    // Customize tab / space per file.
    // Makefile doesn't like space, so use tab
    "[makefile]": {
        "editor.insertSpaces": false,
        "editor.detectIndentation": false
    },
    // Insert spaces when pressing Tab.
    "editor.insertSpaces": true,
    // When opening a file, `editor.tabSize` and `editor.insertSpaces` will be detected based on the file contents.
    "editor.detectIndentation": false,
    "C_Cpp.errorSquiggles": "Disabled",
    "editor.formatOnSave": false,
    "shellcheck.exclude": ["SC1091"],
}
```

## List of steps performed

These steps are supposed to make diff and merge easier...

To know :

Step 1
* Remove extra spaces
* convert all files to unix format. Why Unix and not Windows, because you have to choose one to harmonize and I work under Linux :p

2nd step
* Use vscode to reformat .c, .h files (mainly, but not only)

Step 3
* Perform diff and merge. It's mainly reporting the missing bits of code from tinycc and isolating all that via #ifdef and #ifndef

> These steps are just for information and are already done on pvsneslib (in the PR) and tinycc (in my fork) for versions 0.9.23 and 0.9.24 (I'll let you know as soon as the other branches are done ).

#### pvsneslib/compiler/tcc-816 side

How I proceeded

```bash
# Get my fork of pvsneslib and create my working branch
git clone https://github.com/kobenairb/pvsneslib.git
git submodule update --init // utiliseé plus tard ...
git fetch --all
git checkout stick_to_tinycc-0.9.23

# Trimming white spaces (exclude anything that is not an ASCII file)
find compiler/tcc-816 -not \( -name .svn -prune -o -name .git -prune \) -type f -exec file {} \; | grep ASCII | cut -d ":" -f1 | xargs perl -pi -e 's/ +$//'

# Convert files to unix format (dos2unix only modifies ASCII type files)
find . -not \( -name .git -prune -o -name .svn -prune \) -type f -exec dos2unix {} \;

# Add changes and commit
git add compiler/tcc-816
git commit -m "Remove trailing white space and Format file to Unix format"

```

#### Tinycc side

First of all, I forked the tinycc project from github and created a branch by tag in order to make the same changes to it as for pvsneslib.

```bash
# Get my fork of pvsneslib and create my working branch
git clone https://github.com/kobenairb/tinycc.git
cd tinycc
git fetch --all

# Create a branch by version (tag)
for i in $(git tag | grep -Ev 'initial|release_0_9_1'); do
    git checkout tags/$i -b pvsneslib_$i
    git co -
done

# Apply the same changes as for tcc-816
for i in $(git branch | grep -v mob | awk '{print $1}'); do
    git co $i
    find . -not \( -name .svn -prune -o -name .git -prune \) -type f -exec file {} \; | grep ASCII | cut -d ":" -f1 | xargs perl -pi -e 's/ +$//'
    find . -not \( -name .git -prune -o -name .svn -prune \) -type f -exec dos2unix {} \;
done

# Add changes, commit and push everything to my fork
git add .
git commit -m "Remove trailing white space and Format file to Unix format"
git co mob
git push --all origin
```

### Step 2: Use vscode to reformat .c and .h files

This part is not automatic, vscode does not allow you to do this from the command line, but you can still speed up the process.

Set the auto formatting option to true in the workspace settings

```json
 "editor.formatOnSave": true,
```

Remember to change back to false after completing these steps.

These steps are performed on my working branch of pvsneslib/compiler/tcc-816 and tinycc branches (versions 0.9.23 and 0.9.24 to date)

```bash
# I look for files that differ and edit them on the fly in vscode
diff -qr tinycc pvsneslib-kob/compiler/tcc-65816 | grep ^Files | grep -E '\.c|\.h' | awk '{print $2}' | xargs code
```
Make a CTRL + s on each edited file, the option editor.formatOnSave activated does the job.

Add and commit changes each time.

Same but for non-source files (.pl, text files).

```bash
# I look for files that differ and edit them on the fly in vscode
diff -qr tinycc pvsneslib-kob/compiler/tcc-65816 | grep ^Files | grep -vE '\.c|\.h' | awk '{print $2}' | xargs code
```
Make a CTRL + s on each edited file, the option editor.formatOnSave activated does the job.

Add and commit changes each time.

### Step 3: Diff et Merge

There I look for the source files that differ and I diff them directly in vscode

```bash
diff -qr tinycc pvsneslib-kob/compiler/tcc-65816 | grep ^Files | grep -E '\.c|\.h' | awk '{print $2, $4}' | xargs code --diff
```
And there is more to merge :) Basically, it consists of reporting the missing pieces of code from tinycc and isolating the pieces of code specific to pvsneslib via blocks #ifdef and #ifndef TCC_TARGET_816

Add changes to working branch and commit

## Test changes

With almost each modification, I did the following tests

* the compilation of pvsneslib passes without errors (Makefile at the root of the project)
* the roms (*.sfc) have not changed between the master branch and my working branch of pvsneslib. To do this I cloned the master branch at the root of the project and executed this script at each modification step

```bash
# I clone master at the root of my workspace
git clone -b master https://github.com/kobenairb/pvsneslib.git pvsneslib-master
cd pvsneslib-master
git submodule update --init
export PVSNESLIB_HOME=$(pwd)
make
# I go back to my repositories...
cd ../pvsneslib
```

Then I add my build & test script to the root of my workspace

```bash
#!/bin/bash

function f_make {
    make 2>&1 | tee /var/tmp/make.log
}

function f_check_tcc {
    if [[ "$(md5sum ${PVSNESLIB_HOME}/devkitsnes/bin/816-tcc | cut -d " " -f1)" == "$(md5sum ${PVSNESLIB_HOME_DEFAULT}/devkitsnes/bin/816-tcc | cut -d " " -f1)" ]]; then
        echo "  >>>> 816-tcc IS SAME"
    else
        echo "  >>>> 816-tcc IS DIFFERENT"
    fi
}

function f_check_sfc {
    for i in $(find ${PVSNESLIB_HOME}/snes-examples -type f -name "*.sfc" | grep -v '/bin/'); do
        if [[ "$(md5sum $i | cut -d " " -f1)" != "$(md5sum ${PVSNESLIB_HOME_DEFAULT}/$i | cut -d " " -f1)" ]]; then
            echo "  >>>> $i IS CHANGED, PLEASE CHECK IT"
        fi
    done
}

function f_make_clean {
    make clean
}

# M A I N

# My current repository to work
PVSNESLIB_HOME="$(pwd)"
# My default master repository to compare
PVSNESLIB_HOME_DEFAULT="/home/kobenairb/workspace/pvsneslib-master"

export PVSNESLIB_HOME PVSNESLIB_HOME_DEFAULT

clear

f_make_clean >/dev/null 2>&1 &&
    f_make &&
    echo &&
    f_check_tcc &&
    echo &&
    f_check_sfc &&
    echo &&
    f_make_clean >/dev/null 2>&1
```

Each time the script gives me a difference in the hash of sfc files, I test them via my emulator. Luckily I never had one :)

## Other Changes

I took the initiative to:

* put the gcctestsuite.sh script in bash mode and apply best practices and do the same in tinycc
* ditto for the configure script (test by deleting the config.mak and config.h files). I didn't touch the tinycc one.

I applied vscode formatting on the texi2pod.pl perl script on both sides (pvsneslib and tinycc)

Voila !

Now it's easier to integrate the modifications of the 0.9.24 of tinycc. I tried it without success. tcc compiles without errors but sfc do not.

## Next step to do: migrate to 0.9.24 of tinycc

Switch to the 0.9.24 of tinycc (pvsneslib_release_0_9_24 branch)

Then look for the source files that differ and merge them directly in vscode

```bash
diff -qr tinycc pvsneslib-kob/compiler/tcc-65816 | grep ^Files | grep -E '\.c|\.h' | awk '{print $2, $4}' | xargs code --diff
```

### CODE REVIEW

**Comment by RetroAntho** [comment]
Your explanations are really complete and clear. It is a huge subject you began :)

By seeing your work way, i found the md5 checksum you did to validate result is very usefull and could be implemented directly in PVsneslib. It could help to migrate easily other tools like WLA which still require a lot of tests.

You speak about migrate to 0.9.24 but the last version is 0.9.27 from the official git repository : https://repo.or.cz/tinycc.git
Is it to do it smoothly (to the 0.9.24 version then to 0.9.27) ?

As TCC do not evolve, we should keep it in a specific branch while the upgrade to a new version is not ready.

You mention that tcc compiles correctly but not sfc. Maybe we can check with the hello_world sample if the file produced by both tcc versions are the same ?

**Comment by kobenairb** [comment]
Hi AnthoRetro,

 I think it's easier to migrate step by step, I mean version per version but maybe I'm wrong. I don't remember since which version of tinycc, but I remember that at a moment, they completly change the source code. So the diff & merge could be harder if we decide to directly switch to the latest version of tinycc. I like to proceed step by step but once again maybe I'm wrong. I will try to find the said version where everything changes as soon as I get home. I work from the philippines and the jet lag is big :). About my fork of tinycc I used the non official tinyCC repository on github here https://github.com/TinyCC/tinycc, but it seems to be keep up2date compare to https://repo.or.cz/tinycc.git and it was easier for me to fork it and take as a starting point.

"You mention that tcc compiles correctly but not sfc. Maybe we can check with the hello_world sample if the .asm file produced by both tcc versions are the same ?", okay I check it as soon as I'm at home to show you my logs, from my remember it failed on a asm file during the build process. I just noticed it's easy to modify the libraries without side effects (*.h)  but it's harder with the tcc.c et tccelf.c. I keep you informed as soon I can reproduce the error.

**Comment by alekmaul** [comment]
ok, thanks a lot for this big work on tcc.
just tell me when you think I can do the merge on develop branch

**Comment by kobenairb** [comment]
Hi,

 I finally can migrate tcc to 0.9.24, I just added a new PR.

**Comment by RetroAntho** [comment]
As discussed with kobenairb here : https://github.com/alekmaul/pvsneslib/pull/113
this pull request can be closed (everything is in the new one)

Thank you for your work

**Pull request closed without merging**
