### PR TITLE
feat: a function to enable DMA channels

### PR DESCRIPTION
**Pull request by malayli**
# Description
A function to enable DMA channels.

# Tasks
- [ ] Need review of @alekmaul

### CODE REVIEW

**Comment by RetroAntho** [comment]
Hello, i think it could be interesting to create constants (defines) of all HDMA channels to improve readability of :
enableDmaChannels(0b11000000) enables channels 7 and 6

**Comment by RetroAntho** [comment]
If you think it will be usefull, yes you can add it in this PR. Otherwise it is not urgent, it can be done later!

**Comment by alekmaul** [comment]
I want to review this pull request. Please, give me some time to check this one ^^ we are too fast with the PR ;)

**Comment by alekmaul** [comment]
and we have a function for dma channels: void setModeHdmaReset(u8 channels)
we can perhaps change this one instead of adding a new one if we need something need with hdma activation ;)
also your code is not correct, we need a phb / plb and not the sep rep as you did. Check the existing function, you will see ;)

**Comment by malayli** [comment]
@alekmaul Oh nice thank you. I will close this PR then!
Just to improve my knowledge about this function:
```
setModeHdmaReset:
    php

    sep #$20
    lda 5,s
    sta.l REG_HDMAEN

    plp                                        
    rtl
```
Why do we have `lda 5,s`? what is the meaning of `5,s`?
What is the role of php and plp?

Thank you!

**Comment by alekmaul** [comment]
phb and plb save the flags on stack. It is only 1 byte. This is the reason why we uses ,$ after and not $4.
you need to use it because you use sep $20 to change the state of 65c816 regarding the way registers are managed.
As I said, it is really the same function as the Reset one, so I think you can remove your PR, I will not validate it ;)

**Comment by malayli** [comment]
@alekmaul Ok closed.

**Pull request closed without merging**
