### PR TITLE
Add struct to oam attributes

### PR DESCRIPTION
**Pull request by SirMacho2**
Add a struct to oam attributes to make code more readable.

### CODE REVIEW

**Comment by RetroAntho** [comment]
Hi,
Thank you for this pull request but you cloned the master branch, not the develop one so there are some conflicts to solve.

i do not think that it is a good idea to use struct and union as we know that it is not optimized at all and not recommended with our current version of tcc.

I think we should compare asm generated first and ensure that we do not have lower performances.
Are you fluent with asm to do it?

Also, i guess that sample will required some adaptations to work too.

**Comment by alekmaul** [comment]
that's right, we can't accept this PR, sorry.

**Comment by RetroAntho** [comment]
No, it is same recommendations than for cc65. But this is the reason why the PR is still opened: to check the asm generated and to identify if it will produce any impact as this improvement is good for readability

**Comment by alekmaul** [comment]
@jeffythedragonslayer , why working on this PR which has conflict ? 
Also, before doing such update, I need to you if the assembly code generated is still efficient regarding the current implementation ?

**Comment by alekmaul** [comment]
I do not have a problem with indentation, it is certainly you editor which is not good for that.

**Comment by RetroAntho** [comment]
If the PR stay closed, i guess we will forget it and never finish the check!
Even if we never merge this one, we have all required code to compare it.

@jeffythedragonslayer which kind of work do you speak?

**Comment by alekmaul** [comment]
this is the reason why you have differences. It is not a bug, we will not fix it

**Pull request closed without merging**
