### PR TITLE
few changes on sprites size and makefiles

### PR DESCRIPTION
**Pull request by RetroAntho**
Replace OBJ_SIZE* by OBJ_SIZE*_L* and added other available size.
Remove devkitsnes path in all makefile to use an environment variable

### CODE REVIEW

**Comment by RetroAntho** [comment]
For the 2nd commit (with new samples), please check code because i encountered some problems :
- music sample is renamed : musicSmallerThan32k
- i created a new one musicGreaterThan32k with street of rage 2 music but this one doesn't respect snesmode requirement and has some glitch. Could you please replace by an other that works better ? A new sample explaining how to load directly .spc file should be very useful too.
- collide sample : a simple function to show collide for SNES but i would like to use REG_OBSEL value to find smallSize and largeSize automatically. This part is commented but this sample works. Does anybody know how to do it ? (maybe it should be usefull to implement it directly in oamInitGfxSet function...)
- LoadSecondSprite sample under graphics/Sprites : this one have a real bug and the 2nd sprite doesn't appear to the screen (but is loaded correctly). Could you please explain me what is the cause ?

**Comment by RetroAntho** [comment]
To solve music issue in musicGreaterThan32k sample (the glitch in street of rage 2 music). I propose to use this one that works perfectly :)

I took it from [this topic](https://forums.nesdev.com/viewtopic.php?f=12&t=11382&start=60) on nesdev.com. I asked to developer of this juke box it is usable without restriction but never get response.

[21-whatislove.it.zip](https://github.com/alekmaul/pvsneslib/files/3194299/21-whatislove.it.zip)

**Comment by RetroAntho** [comment]
Reminder on 2 things to check for this pull request :)

- collide sample : to improve samples, it should be interesting to use REG_OBSEL to find small size and large size of a sprite but i need help. I think it should be better to create this 2 variables directly in PVSneslib and set values while calling oamInitGfxSet function.

LoadSecondSprite sample under graphics/Sprites : this one have a real bug and the 2nd sprite doesn't appear to the screen (but is loaded correctly). Could you please help me to solve it ?

**Comment by alekmaul** [comment]
Rejected as it was added manually in master

**Pull request closed without merging**
