### PR TITLE
feat: add function to insert Mesen breakpoint using the 65816's WDM opcode

### PR DESCRIPTION
**Pull request by jeffythedragonslayer**
I do think we should eventually move this to a file called emulators.asm eventually, but it's a start so people on the develop branch can get some experience using it.

Make sure you have "Break on" WDM checked in Mesen 2's debugger.

### CODE REVIEW

**Comment by RetroAntho** [comment]
Thank you for this update. May i ask you a sample to and/or wiki page to explain how it works and need to be used?

**Comment by alekmaul** [comment]
> I don't think I have write access to the wiki. Should I use https://wiki.superfamicom.org instead?

well, you can add an example in snes-examples folder

**Comment by alekmaul** [comment]
and please update console.h with the prototype of the function
I can accept the pull request without it

**Comment by RetroAntho** [comment]
If you want to do a page for the wiki, you can do it in your own repository then provide us the markdown file. We will have better way to do it soon

**Comment by RetroAntho** [comment]
Replaced by this PR:

https://github.com/alekmaul/pvsneslib/pull/172

**Pull request closed without merging**
