### PR TITLE
Code cleaning

### PR DESCRIPTION
**Pull request by kobenairb**
Hi,

A PR to standardize the code (coding convention) for C and ++ files as well as the addition of a settings.json file for **vscode** so that we all follow the same rules without asking questions. The `readme` under `vscode-templates` is also updated. Other than that nothing changes.

@RetroAntho : 
I haven't found anything conclusive under vscode or other command line tools to format assembly code. And to say that it was native under ZX Spectrum :)

### CODE REVIEW

**Comment by RetroAntho** [comment]
Hi,

now you did it, i am aksing why some extensions have been created to do the same thing :) I used .editorconfig (with editor config extension) to enforce coding style.

I think it is a good idea to use settings.json, but as it is done on client side, it require that you use vscode. I do not know if Alekmaul use it each time.

This merge request will produce some conflicts and Alekmaul have probably some local files not pushed for now. we should keep only your first commit and the 2nd one (where rules are applied) will be done by Alekmaul when everything will be ready to push

**Comment by RetroAntho** [comment]
For your remark about indentation of the assembly code, i do not know how it will be hard to write a piece of code to do it. Maybe better than searching a tool which will not works as we want?

**Comment by kobenairb** [comment]
Yes I'm completely agree with you. It was just a proposition. Whatever
we'll need to synchronise all together to do it. As you say, Alek is using
this branch daily to test. And of course it's not perfect, it's first
supposed that we'll all using vscode. Otherwise I can add a script to
format it in the same way without to need to use vscode. It's just few
bash. I can do the same with clang-formater with the same options. My idea
was to add like a coding convention because it's hurt my eyes when I was
trying to update tcc. Just let this pr wait until we can find an
appropriate way to do it.

Le sam. 24 sept. 2022, 22:40, RetroAntho ***@***.***> a
écrit :

**Comment by kobenairb** [comment]
Yes maybe just a few python will make the job. It was to avoid to add more
complexity to this project like 816-opt.py. but I can't really find a good
way to do it with existing tools. Or maybe with Emac with a macro, but once
again it adds more complexity. I''m see if I can code it by using opcodes
and mnemonics from the 65817. I'm not able to develop it directly as a
plugin for vscode.

Le sam. 24 sept. 2022, 22:44, RetroAntho ***@***.***> a
écrit :

**Comment by kobenairb** [comment]
By the way, I tried to test the new version of tcc directly in the develop
branch but I noticed some regressions. For example, the timer didn't work
anymore, I had a pink screen in the emulator. I just let Alek finish his
work, I'll try it once again later.

**Review by alekmaul — APPROVED** [review]

**Comment by kobenairb** [comment]
Otherwise we can use pre commit hooks but it's always, it's up to the
contributor to activate it or not. Most of time this job is made during the
pipeline of continuous integration. It's not really important by the way.
It's just ergonomic.

Le sam. 24 sept. 2022, 22:40, RetroAntho ***@***.***> a
écrit :

**Pull request merged**
