### PR TITLE
[WIP] upgrade to wla 9.11 version

### PR DESCRIPTION
**Pull request by hoit**
Hi,

this is modifications i did to upgrade current PVSneslib on wla 9.8.
(I didn't find a way to create a 2nd pull request with RetroAntho account that why i use this one)

Why choose to upgrade wla at first ?
i think this is really important because the previous version has more than 10 years, no more help on it, new functionalities has been added, improvements and optimisations... This is the 1st step to improve the lib (tcc should be the next !).
With this new version, i think some bugs will be solved and snestool could be replaced by patching the rom with wla directly. Why not using it to upgrade snesmod in the future instead of using tasm ? :)

What about this upgrade ?
For now, it build correctly but it doesn't work : nothing appear to the screen (text, background or sprites) so if somebody can help me i will be happy because i didn't find the root cause.

It use official wla 9.8 (from github) which has been adapted by VHelin to build correctly.
tcc816 has been rebuild with only this change in 816-gen.c :
`char* static_prefix = "tccs_";`
I removed the "__" before because with WLA 9.8, if you have a label that begins with a _ and it is inside a section,  then the name doesn't show outside of that section. If it is not inside a section it doesn't show outside of the object file...

I just have few remarks about last PVSneslib commit : 
- all sources from super scope has been removed. Does it have any bugs ?
- in scores.asm, new label have been created and start with a "_". I think it will produce compilation error due to scope of items with underscore.
- 816-opt.py : few parts of code has been removed from file in devkitsnes folder but are still existing in compiler one. I guess that is voluntary, should we use the one in devkitsnes folder ?

### CODE REVIEW

**Comment by alekmaul** [comment]
Thanks a lot, I will check it next week, it seems that it has no conflict with master.
Regarding superscope, i can't test it as I do not have a flat TV and a superscopre. Regarding score.asm, strange, need to check.
About the py file, i really don't know :O, need to check

**Comment by hoit** [comment]
No conflict but it doesn’t work for now. i hope you will find where is the bug :)
I am still checking!
for superscope, i will ask around me if i can borrow it to check the code of the lib.

**Comment by hoit** [comment]
Hello, does someone else is interested by upgrading the version of wla?

**Comment by alekmaul** [comment]
yes, sorry, I was very busy with lots of projects.
I think it is interesting to update wla but the big bottleneck is the comptiler tcc816. It is the man part of non opimization code (this is also the reason why we have a python file to optimize its code).

**Comment by hoit** [comment]
There is more than 11 years between the version used by the lib and the last wla version. I think we can find last improvements history but we will not find all details.
To Work on this upgrade, i opened an [issue](https://github.com/vhelin/wla-dx/issues/232) on wla’s git which provide few informations. Few functionalities were created in wla 9.4 for tcc816 and the owner of wla implemented it in the new version to provide us same functionalities for this upgrade.
The way to build changed a little bit and variables which begin with _ have now a different scope that is why i removed it everywhere.

Now the latest wla version is 9.11 but i think the work to finish the upgrade will be the same than 9.8.

I totally agree and tcc816 should be improved too,but it is based on wla and the project is not maintained anymore that is why i began with wla!

**Comment by alekmaul** [comment]
Let's go to begin the upgrade of wla, tcc will be the next step and I think we will also try to add another way to discuss about the lib and how to improve it ;)

**Comment by hoit** [comment]
I tried the newest wla version 9.11 (instead of 9.8) ([exe available here](https://www.villehelin.com/wla-win32.html))
The build of pvsneslib failed here :
libc.obj: pads.asm:104: FIX_REFERENCES: Value ($1b0) of "snes_mplay5" is too much to be a 8-bit value.

`line 104 : stz.b snes_mplay5 ; currently no Multiplay5 connected`
i am not sure but i think i only need to remove sep #$20 from the function because the documentation explain "When the m flag is 0, LDA, STA, and STZ are 16-bit operations, and when the m flag is 1, LDA, STA, and STZ are 8-bit operations".

This step build now correctly.

The next one is strange and appear between 9.8 and 9.11 (because the file has not been changed since 3 years) :
CHECK_FILE_TYPES: File "sm_spc.obj" is of unknown format ("═ Þ ").

I asked on the opened subject on wla github.

In the output during the build, i also seen : 

_consoles.asm:28: WARNING: There is a SLOT number 0, but there also is a SLOT (with ID 1) with starting address 0 ($0)... Using SLOT 0.
sprites.asm:37: WARNING: There is a SLOT number 0, but there also is a SLOT (with ID 1) with starting address 0 ($0)... Using SLOT 0._

maybe it will explain us the first issue where nothing appeared to the screen

**Comment by alekmaul** [comment]
really strange, I tought we always need to specify the 8/16 size before doing a  stz.b ... :/
Regarding WARNING, I think the root cause is : .ramsection ".reg_cons7e" bank $7e slot 0
Same thing in sprites.asm : .ramsection ".reg_oams7e" bank $7e slot 0

Perhaps we can't declare more than 1 ram section on same slot with newest wla ?

**Comment by hoit** [comment]
Hi, i did some changes to use the new wla 9.11.

What does works correctly ?

I tried basic samples like hello world, Mode 0 and simple sprite !

What does not work for now ? (and i need help !)

The music and sound sample does not work: they build correctly but the sound/music is never played.
Same thing with Mario sample and nothing display on the screen.

Improvements:

I do not know why but in lot of sample, the .obj files are not removed anymore by make clean command. I just added *.obj to solve it quickly.

Makefiles should be improved in the project to avoid hard coded path which is different for each user.

If you get this issue :

CHECK_FILE_TYPES: File "xxx.obj" is of unknown format ("═ Þ ").
you need to remove .obj files from project and the newest .obj files from PVSNESlib will be copied (it is probably because the .obj files in the current folder are build with an different version of wla 9.11).

**Comment by alekmaul** [comment]
I do not forget this merge request, just too busy. I will check it soon, don't worry.

**Pull request merged**
