### PR TITLE
Add dockerfile for linux

### PR DESCRIPTION
**Pull request by kobenairb**
Hi all,

 Here a PR to add possibility to compile source code with docker linux containers (fedora, debian and ubuntu). More details and information in the `readme.md` under the docker/ directory.

### CODE REVIEW

**Comment by alekmaul** [comment]
Ok, we will check your PR as soon as possible

**Comment by alekmaul** [comment]
thanks , I will check your merge request and test it. Nice to see someone working on docker intergration.
As for other merge request, it will begreat to use develop branch ;)  ?

**Comment by kobenairb** [comment]
Okay, I modify my PR to develop branch, same for the PR for the 816-opt.py. It should be done in few hours.

**Comment by kobenairb** [comment]
Done

**Comment by alekmaul** [comment]
Merge done! thanks !

**Comment by RetroAntho** [comment]
Hi, i have a question: what is the goal to have a docker image by operating system?

**Comment by RetroAntho** [comment]
Found a typo in readme :   git clone git clone https://github.com/alekmaul/pvsneslib.git

**Comment by kobenairb** [comment]
Hi Antho,

The goal is to cover the most used distributions. The lib and compiler versions differ from one OS to another. The idea is to easily report any regression by testing different environments. This can be useful for those who want to compile the code standalone on their machine and avoid issues like; "I have errors while compiling on my distro". Obviously it's not perfect because I'm using the latest images so it doesn't cover all scenarios.

**Comment by alekmaul** [comment]
yeah, I agree with kobenairb.  It is not easy to check all image version instead of latest. Let's begin with this file, we will see the comments :)

**Comment by RetroAntho** [comment]
Ok thank you, it is more clear :)

**Pull request merged**
