### PR TITLE
update tcc to 0.9.24

### PR DESCRIPTION
**Pull request by kobenairb**
Hi,

I finished migrating tcc-65816 to version 0.9.24. Everything went well

Just a point when creating the Mode1ContinuousScroll.sfc rom with wla, I had to do a fix (line 9079) of `tcc.c`.

```c
// Fix for Mode1ContinuousScroll.sfc, otherwise sfc is not built
#ifdef TCC_TARGET_816
            vseti(VT_JMP, gtst(1, 0));
#else
        {
            save_regs(1);
            vseti(VT_JMP, gtst(1, 0));
      
        }
#endif
```

If I keep save_regs(1);, the rom is not created without more message than that despite the verbose mode activated. Hence my question, is this correct or should we modify the lib and or the c code of the rom?

I'll let you look at that, just to be sure that I haven't forgotten anything.

So you can close / delete my previous PR on the preparation of the migration with the code in 0.9.23 I think.

Just to precise, compilation is okay without new warning and rom are identicals (cksum)

### CODE REVIEW

**Comment by RetroAntho** [comment]
Hi kobenairb,

Well, it is a very good job :)
We are just discussing on Discord about an issue on the current TCC version. (Do not hesitate to join us, but this discussion is in french)
I would like to know if this bug is solved in this new version :

```
#include<snes.h>

u8 line_complete = 0;
u32 wait = 0;

void main (void)
{
    consoleInit();

    while(1)
    { 
        line_complete = 0;
        scanPads();
        if(padsCurrent(0) & KEY_SELECT)
        {
            consoleNocashMessage("SELECT PRESSED\n" );
            if ((line_complete != 0) && (wait==0))
            {
                consoleNocashMessage("line : %d\n",(u16)line_complete);
            }
        }
        WaitForVBlank();
    }
}
```

This piece of code print in No$sns :` "line : ..."` when you push select, but it should not be the case. It is due to the asm generated which is wrong.

Also, the current tcc version we use do not work in 64 bits, maybe this new version will now works.

For your question about `save_regs(1);`, i do not know what is the goal of this function but it is strange to have an issue only for one rom. I read the content of the function but it is not clear at all for me, it is really specific to asm that i do not read correctly.
To avoid issues in the future, i think it is more sure to understand why it does not work for one example instead of removing it

**Comment by kobenairb** [comment]
Hi alek, I'll be glad next next time but it's already 1am here and I'm
falling asleep.

Je suis français aussi 😆 n'hésitez à me faire des retours, je suis sûr
d'avoir oublié des trucs.

Brian

Le mar. 13 sept. 2022, 01:01, RetroAntho ***@***.***> a
écrit :

**Comment by RetroAntho** [comment]
It is not Alekmaul :)
I just cloned your repository and did some tests :
```
#include<snes.h>

u8 line_complete = 0;
u32 wait = 0;

void main (void)
{
    consoleInit();

    while(1)
    { 
        line_complete = 0;
        scanPads();
        if(padsCurrent(0) & KEY_SELECT)
        {
            consoleNocashMessage("SELECT PRESSED\n" );
            if ((line_complete != 0) && (wait==0))
            {
                consoleNocashMessage("line : %d\n",(u16)line_complete);
            }
        }
        WaitForVBlank();
    }
}
```
- This code still have the bug and print in no$sns the information "line : 0"
It is probably related to the implementation of 65c816 in the code so the upgrade will not help us, we will need to investigate further in the code if we want to solve it

- I also tried to build it in 64bits (without -m32 CFLAGS) and it still produce the core dump :(
We can hope it is solved in the 0.9.27 version because we thought it comes from these commit:
https://github.com/adorad/tcc/commit/bed17847bdfa872e219a12237e06df83e464bdba
https://github.com/adorad/tcc/commit/d0b432ab38b09cd167d8a8065ffe1e14878d6e2d?diff=split

I did not checked more the part about `save_regs(1);`

This is the link if you want to join us on discord : https://discord.gg/DzEFnhB (will be more easy to speak in french !)

See you soon :)

**Comment by kobenairb** [comment]
Hi,

 Sorry for my long silence, I was not very available and practically without internet access.

 I made some advances regarding tcc.

 I am finishing 25, and I can now compile tcc in 64 bits and compile advanced roms

 The link if you want to take a look at it, it's not finished, in the sense that I'm somewhere between version 24 and 25 before bump : https://github.com/kobenairb/pvsneslib/tree/prerelease_tinycc-pvsneslib-0.9.25

 So, we can close this PR.

 I should have a 26 available for the weekend.

 An idea to submit to you:
- Can we consider in the future to do with tcc 816 the same thing as for WLA? For example, create a repo at Alek with the name of the directory that hosts it and make a submodule. I think it would avoid polluting pvsneslib in PR and it would allow testing faster when upgrading. Also it allows to better expose the work of Alek because this compiler is not very visible because it is integrated into pvsneslib. Maybe others will be seduced and will come and participate. And in the future, once arrived in 27, why not the committer on tinycc which have a large community.

@RetroAntho: normally it should pass without worries on ARM, I modified the Makefile. On the other hand I went back to configure tinycc, I see to backport your modifications once in 27

If I have time, I would also like to switch the python optimizer to C and integrate it into tcc via an option, as Alek had started doing

**Comment by RetroAntho** [comment]
Hi !

Do not worry, it is not urgent and we are all busy with a lot of things.

It is a very good news if it now works in 64b without producing the segmentation fault.

I agree too with the idea to do a specific repository for TCC, but i do not advise to call it "only" TCC. To avoid confusion, as it is not a fork or an official version and it is a port, i think it should be something like tcc65c (tcc816 provide less information when you hear the name) or tcc65c816 if we want to be (too much?) precise.

I do not have the time to test your work for now, but i will be happy to do it soon !

If you developed some scripts to do the checksum on files/rom or anything to check it easily, i think it will be good to keep it somewhere in the library (or add it in the wiki in a new page) to improve the way we do upgrade.

For your last remark, 3 things could be interesting to do in the future :
- As you said, remove the python optimiser to do it directly in C
- To do the same thing with constify tool (which move "const" variables from RAM to ROM in the .asm files)
- Find a way to indent automatically the asm file generated, but it is a "nice to have"

See you soon !

**Comment by alekmaul** [comment]
tcc seems ok as it is still generic for all processor, with the 65c816 addon.
I think we can use my tcc repository now.
@kobenairb , tell me if you can push in it. You can begin to work with master as it is a fresh repository.

**Comment by alekmaul** [comment]
Adding constify to tcc will not be easy as you will have to manage with rom banks (if you're not aware of that, you will be limited of 32K consts). 
I think we can try to have an unique tool for optim+constify+beautify&format code to do the job after tcc.

**Comment by kobenairb** [comment]
> It is not Alekmaul :) I just cloned your repository and did some tests :
> 
> ```
> #include<snes.h>
> 
> u8 line_complete = 0;
> u32 wait = 0;
> 
> void main (void)
> {
>     consoleInit();
> 
>     while(1)
>     { 
>         line_complete = 0;
>         scanPads();
>         if(padsCurrent(0) & KEY_SELECT)
>         {
>             consoleNocashMessage("SELECT PRESSED\n" );
>             if ((line_complete != 0) && (wait==0))
>             {
>                 consoleNocashMessage("line : %d\n",(u16)line_complete);
>             }
>         }
>         WaitForVBlank();
>     }
> }
> ```
> 
> * This code still have the bug and print in no$sns the information "line : 0"
>   It is probably related to the implementation of 65c816 in the code so the upgrade will not help us, we will need to investigate further in the code if we want to solve it
> * I also tried to build it in 64bits (without -m32 CFLAGS) and it still produce the core dump :(
>   We can hope it is solved in the 0.9.27 version because we thought it comes from these commit:
>   [adorad/tcc@bed1784](https://github.com/adorad/tcc/commit/bed17847bdfa872e219a12237e06df83e464bdba)
>   [adorad/tcc@d0b432a?diff=split](https://github.com/adorad/tcc/commit/d0b432ab38b09cd167d8a8065ffe1e14878d6e2d?diff=split)
> 
> I did not checked more the part about `save_regs(1);`
> 
> This is the link if you want to join us on discord : https://discord.gg/DzEFnhB (will be more easy to speak in french !)
> 
> See you soon :)

Hi RetroAntho,

it works for me:

```
/*---------------------------------------------------------------------------------


	Simple console 'hello world' demo
	-- alekmaul


---------------------------------------------------------------------------------*/
#include<snes.h>

extern char snesfont;

//---------------------------------------------------------------------------------
int main(void) {
    // Initialize SNES
	consoleInit();

    // Initialize text console with our font
	consoleInitText(0, 0, &snesfont);

	// Draw a wonderfull text :P
	consoleDrawText(5,8,"TESTING PAD");
	consoleDrawText(3,10,"PRESS ANY KEY");

	// Now Put in 16 color mode and disable Bgs except current
	setMode(BG_MODE1,0);  bgSetDisable(1);  bgSetDisable(2);

	// Wait for nothing :P
	setBrightness(0xF);

	while(1) {

        scanPads();
        if(padsCurrent(0) & KEY_SELECT)
        {
            consoleDrawText(6,12,"KEY PRESSED=%s","SELECT");
        }
        WaitForVBlank();
	}
	return 0;
}
```
Keep me informed :)

**Comment by RetroAntho** [comment]
Hi @kobenairb,

yes but you removed the parts in the code which produce the bug :)

`if ((line_complete != 0) && (wait==0))`

**Pull request closed without merging**
